version: "3"
#Creation de l'image
services:
  mongo:
    image: mongo:3.2.4
    ports:
      - 27017:27017
    command: --smallfiles
#Parametre de connexion
  mongo-client:
    image: mongoclient/mongoclient
    ports:
      - 3030:3000
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
    links:
      - mongo